# basic options, i can say what ever here
title: New awesome blog
author: eungjin cho
email: your-email@domain.com
description: A wonderful site
twitter_username: choshim
github_username:  choeungjin

# Build settings
markdown: kramdown
theme: minima
